/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in many projects. It is checked in here so
// `npm run typecheck` has stable type references before the first dev-server run.

